server:
  port: 8082

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    
jwt:
  key: ENC(uCdWdUO98T+K09Z1fKH2DUT5WaRdkJh5P/En/qyelZAOpYcw1GFFhx56Tkt/JoOVl7ze6XIHQKN6G5QWUvk9QPyyhNE9tQQpPDEiweFGptEraFDukChMSr6N4rnnHbFFpXmqW5Hm4WIXLihrbxqASA==)
  expiration: 604800000 # 7 days

refresh-token:
  expiration: 30 # 30 days
  
spring:
  # default profile
  profiles:
    active: dev
    
  application:
    name: businesscard

  liquibase:
    change-log: classpath:/liquibase/master.yml

  datasource:
    url: jdbc:mysql://localhost:3306/businesscard-db
    username: algofusion-bc
    password: algofusion-bc_mysql*
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: algofusion-bc-redis
      ssl:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 962806171238-daotkglq7pju8nlandrghh6iod4ed2ih.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
          # facebook:
          #   client-id: YOUR_FACEBOOK_CLIENT_ID
          #   client-secret: YOUR_FACEBOOK_CLIENT_SECRET
          #   scope: public_profile, email
          #   redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          #   authorization-grant-type: authorization_code
          #   client-name: Facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
          # facebook:
          #   authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
          #   token-uri: https://graph.facebook.com/v10.0/oauth/access_token
          #   user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture

