server:
  port: 8082

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    
jwt:
  key: ENC(uCdWdUO98T+K09Z1fKH2DUT5WaRdkJh5P/En/qyelZAOpYcw1GFFhx56Tkt/JoOVl7ze6XIHQKN6G5QWUvk9QPyyhNE9tQQpPDEiweFGptEraFDukChMSr6N4rnnHbFFpXmqW5Hm4WIXLihrbxqASA==)
  expiration: 600000
  
spring:
  # default profile
  profiles:
    active: dev
    
  application:
    name: businesscard

  liquibase:
    change-log: classpath:/liquibase/master.yml

  datasource:
    url: jdbc:mysql://localhost:3306/businesscard-db
    username: algofusion-bc
    password: algofusion-bc_mysql*
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: algofusion-bc-redis
      ssl:
        enabled: false
