services:
  businesscard-mysql:
    image: mysql:latest
    container_name: businesscard-mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: algofusion-bc
      MYSQL_DATABASE: businesscard-db
      MYSQL_USER: algofusion-bc
      MYSQL_PASSWORD: algofusion-bc


  redis:
    image: redis:latest
    container_name: businesscard_redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge