services:
  businesscard-mysql:
    image: mysql:latest
    container_name: businesscard-mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: algofusion-bc_mysql_rp*
      MYSQL_DATABASE: businesscard-db
      MYSQL_USER: algofusion-bc
      MYSQL_PASSWORD: algofusion-bc_mysql*


  businesscard-redis:
    image: redis:latest
    container_name: businesscard_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass algofusion-bc-redis
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge