# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
      # 3. runnin docker container (for MySQL)
    - name: Set up MySQL container
      run: |
        docker run -d \
          --name $MYSQL_CONTAINER_NAME \
          -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD \
          -e MYSQL_DATABASE=$MYSQL_DATABASE \
          -e MYSQL_USER=$MYSQL_USER \
          -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
          -p $MYSQL_PORT:$MYSQL_PORT \
          mysql:$MYSQL_VERSION
      env:
        MYSQL_CONTAINER_NAME: businesscard-mysql-db
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_PORT: 3306
        MYSQL_VERSION: latest
    
    # 2. Çevresel değişkenlerin tanımlanması
    - name: Set up environment variables
      run: |
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $GITHUB_ENV
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_ENV
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
        echo "MYSQL_CONTAINER_NAME=${{ secrets.MYSQL_CONTAINER_NAME }}" >> $GITHUB_ENV
        echo "MYSQL_PORT=3306" >> $GITHUB_ENV
        echo "MYSQL_VERSION=latest" >> $GITHUB_ENV
    

    - name: Wait for MySQL to be ready
      run: |
          until docker exec ${MYSQL_CONTAINER_NAME} mysqladmin --user=root --password=${MYSQL_ROOT_PASSWORD} --host=localhost --port=3306 --silent ping; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

    - name: Build and Test with Maven
      run: mvn clean install -DskipTests=false

      # 7. Docker konteynerini kapatma işlemi
    - name: Stop MySQL container
      run: |
          docker stop ${GITHUB_ENV["MYSQL_CONTAINER_NAME"]}
          docker rm ${GITHUB_ENV["MYSQL_CONTAINER_NAME"]}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    